name = "deploys--registry"
main = "src/index.js"
compatibility_date = "2023-12-01"

[route]
pattern = "registry.deploys.app"
custom_domain = true

[vars]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "deploys-registry"

[[d1_databases]]
binding = "DB"
database_id = "67b907e7-9d0d-4846-851e-8e7da80acbad"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "deploys_registry"
